#!/bin/bash


set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DATADIR=$DIR/data
hasNode=$(qc status -silent)
if [ $? -ne 0 ]; then
    echo "Error Connecting to QredoChain Node"
	exit 1
fi
while getopts 'd' flag; do
  case "${flag}" in
    d) d_flag='true' ;;
   esac
done
if [ -x "$(command -v tabset)" ]; then
    tabset happy
fi
shift $(($OPTIND - 1))e
incomingID=$1



#----------------------------------------------------------------------------------------------------------------------------------------


dump (){
	if [ $d_flag = 'true' ]; then
		echo "debug $debug"
		echo $2
		echo -e "\033[40;31;5;82m $1  \033[0m"	
		res=$(echo $1 | sed 's/"/\\"/g')
		echo -e "\033[40;38;5;82m $res  \033[0m"
	fi
}





#----------------------------------------------------------------------------------------------------------------------------------------

PrepGroupUpdate() {
	echo Prepare Updated Group serialized TX for Signing 

	updateJson='{
		"existingGroupAssetID":"'$incomingID'",
		"newowner":"'$p1_assetid'",
		"transferType":1,
		"group":{
			"type":1,
			"description":"Group Description is here",
			"groupfields":[
				{"key":"groupfield_key1","value":"new_value1"},
				{"key":"groupfield_key2","value":"new_value2"}
			],
			"Participants":[
				{"key":"Participants_key1","value":"new_value1"},
				{"key":"Participants_key2","value":"new_value2"}
			]
		},
		"transfer":[{
			"transferType":1,
			"expression":"t5 + t6 + t7 > 1 & p2",
			"description":"some description goes here",
			"participants":[
				{"name":"p2","ID":"'$p2_assetid'"},
				{"name":"t5","ID":"'$t5_assetid'"},
				{"name":"t6","ID":"'$t6_assetid'"},
				{"name":"t7","ID":"'$t7_assetid'"}
				] }]
		}'

	dump "$updateJson" "PrepGrouUpdate"

	updateJson=$(echo $updateJson | sed 's/\n//g')
	updateGroup=$(qc pgu -j="$updateJson")
	serializedUnsignedAsset=$(echo $updateGroup | jq -r .serializedUpdate)
}
#----------------------------------------------------------------------------------------------------------------------------------------

SignForEachIDoc() {
	echo "Sign for each IDDoc"
	json='{"seed":"'$p2_seed'","msg":"'$serializedUnsignedAsset'"}'
	sigP2=$(qc sign -j="$json" | jq -r .signature)
	json='{"seed":"'$t5_seed'",	"msg":"'$serializedUnsignedAsset'"}'
	sigT5=$(qc sign -j="$json" | jq -r .signature)
	json='{	"seed":"'$t6_seed'",	"msg":"'$serializedUnsignedAsset'"}'
	sigT6=$(qc sign -j="$json" | jq -r .signature)
	json='{	"seed":"'$t7_seed'",	"msg":"'$serializedUnsignedAsset'"}'
	sigT7=$(qc sign -j="$json" | jq -r .signature)
}



#----------------------------------------------------------------------------------------------------------------------------------------

SendGroup() {
	echo SendGroupUpdate - Aggreate Sign, Verify and optionally broadcast
	json='{"sigs":[
				{"id":"'$p2_assetid'","abbreviation":"p2","signature":"'$sigP2'"},
				{"id":"'$t5_assetid'","abbreviation":"t5","signature":"'$sigT5'"},
				{"id":"'$t6_assetid'","abbreviation":"t6","signature":"'$sigT6'"},
				{"id":"'$t7_assetid'","abbreviation":"t7","signature":"'$sigT7'"}
				],
			"GroupUpdatePayload":'$updateJson'
		}'
	dump "$json" "Aggregate Sign"
	updateComplete=$(qc sg -b=true -j="$json")
}

#----------------------------------------------------------------------------------------------------------------------------------------



echo Build Binary
build
source $DATADIR/assets
PrepGroupUpdate
SignForEachIDoc
SendGroup





    
