#!/bin/bash

# Some Stats for reference:
# 40 hour run,  550,000 TXs
# /tmp/example 884M data directory
# assets/libs/app/data/ 669M
# Restart App and re-process all transaction (they will all exsit so will return with "Fail to add IDDoc - tx already in Consensus Database")
# Time taken = 2mins for 0.5million records.
# Large chain set 'ulimit -n 4096'  else too many open files error
#Use -d flag for debug info


DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DATADIR=$DIR/data


hasNode=$(qc status -silent)
if [ $? -ne 0 ]; then
    echo "Error Connecting to QredoChain Node"
	exit 1
fi


#set -e

dump (){
	if [ $d_flag = 'true' ]; then
		echo "debug $debug"
		echo $2
		echo -e "\033[40;31;5;82m $1  \033[0m"	
		res=$(echo $1 | sed 's/"/\\"/g')
		echo -e "\033[40;38;5;82m $res  \033[0m"
	fi
}


newWalletID=$1


#----------------------------------------------------------------------------------------------------------------------------------------

PrepWalletUpdate() {
	echo Prepare Updated Wallet serialized TX for Signing 

	updateJson='{
		"existingWalletAssetID":"'$newWalletID'",
		"newowner":"'$b1_assetid'",
		"transferType":2,
		"currency":"BTC",
		"walletTransfers":[
		    {"to":"01010100ff00","amount":20,"assetid":"00ff00"},
		   	{"to":"02020200ff00","amount":30,"assetid":"00ff01"}
		    ],
		"transfer":[{
			"transferType":2,
			"expression":"t5 + t6 + t7 > 1 & p2",
			"description":"some description goes here",
			"participants":[
				{"name":"p2","ID":"'$p2_assetid'"},
				{"name":"t5","ID":"'$t5_assetid'"},
				{"name":"t6","ID":"'$t6_assetid'"},
				{"name":"t7","ID":"'$t7_assetid'"}
				] }]
		}'

	dump "$updateJson" "PrepWalletUpdate"
	
	updateJson=$(echo $updateJson | sed 's/\n//g')
	updateWallet=$(qc pwu -j="$updateJson")
	serializedUnsignedAsset=$(echo $updateWallet | jq -r .serializedUpdate)
}
#----------------------------------------------------------------------------------------------------------------------------------------

SignForEachIDoc() {
	echo "Sign for each IDDoc"

	#sign for each IDDoc
	json='{"seed":"'$p2_seed'","msg":"'$serializedUnsignedAsset'"}'
	sigP2=$(qc sign -j="$json" | jq -r .signature)
	json='{"seed":"'$t5_seed'",	"msg":"'$serializedUnsignedAsset'"}'
	sigT5=$(qc sign -j="$json" | jq -r .signature)
	json='{	"seed":"'$t6_seed'",	"msg":"'$serializedUnsignedAsset'"}'
	sigT6=$(qc sign -j="$json" | jq -r .signature)
	json='{	"seed":"'$t7_seed'",	"msg":"'$serializedUnsignedAsset'"}'
	sigT7=$(qc sign -j="$json" | jq -r .signature)
}


#----------------------------------------------------------------------------------------------------------------------------------------

SendWallet() {
	echo SendWallet - Aggreate Sign, Verify and optionally broadcast
	json='{"sigs":[
				{"id":"'$p2_assetid'","abbreviation":"p2","signature":"'$sigP2'"},
				{"id":"'$t5_assetid'","abbreviation":"t5","signature":"'$sigT5'"},
				{"id":"'$t6_assetid'","abbreviation":"t6","signature":"'$sigT6'"},
				{"id":"'$t7_assetid'","abbreviation":"t7","signature":"'$sigT7'"}
				],
			"walletUpdatePayload":'$updateJson'
		}'
	dump "$json" "Aggregate Sign"
	updateComplete=$(qc sw -b=true -j="$json")
}




#----------------------------------------------------------------------------------------------------------------------------------------
GetBalance() {
	balance=$(qc balance "$newWalletID"  | jq -r ".amount")	
	echo Balance: $balance
}


#----------------------------------------------------------------------------------------------------------------------------------------

d_flag='false'

while getopts 'd' flag; do
  case "${flag}" in
    d) d_flag='true' ;;
   esac
done


echo Build Binary
build

d_flag='true'
debug=true

if [ -x "$(command -v tabset)" ]; then
    tabset happy
fi

#----------------------------------------------------------------------------------------------------------------------------------------


source $DATADIR/assets
GetBalance
PrepWalletUpdate
SignForEachIDoc
SendWallet
GetBalance





    
