// Code generated by "stringer -type=TransactionCode"; DO NOT EDIT.

package assets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeTypeOK-0]
	_ = x[CodeTypeEncodingError-1]
	_ = x[CodeTypeBadNonce-2]
	_ = x[CodeTypeUnauthorized-3]
	_ = x[CodeAlreadyExists-4]
	_ = x[CodeDatabaseFail-5]
	_ = x[CodeFailVerfication-6]
	_ = x[CodeTypeHTTPError-7]
	_ = x[CodeConsensusBalanceError-8]
	_ = x[CodeConsensusError-9]
	_ = x[CodeInsufficientFunds-10]
	_ = x[CodeTendermintInternalError-999]
}

const (
	_TransactionCode_name_0 = "CodeTypeOKCodeTypeEncodingErrorCodeTypeBadNonceCodeTypeUnauthorizedCodeAlreadyExistsCodeDatabaseFailCodeFailVerficationCodeTypeHTTPErrorCodeConsensusBalanceErrorCodeConsensusErrorCodeInsufficientFunds"
	_TransactionCode_name_1 = "CodeTendermintInternalError"
)

var (
	_TransactionCode_index_0 = [...]uint8{0, 10, 31, 47, 67, 84, 100, 119, 136, 161, 179, 200}
)

func (i TransactionCode) String() string {
	switch {
	case 0 <= i && i <= 10:
		return _TransactionCode_name_0[_TransactionCode_index_0[i]:_TransactionCode_index_0[i+1]]
	case i == 999:
		return _TransactionCode_name_1
	default:
		return "TransactionCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
