echo "clean build"
del *.o
del *.a

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/kem/sike/kem_sike.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/kem/sike/kem_sike.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/kem/sike/P751/P751.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/kem/sike/P751/P751.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/kem/sike/P751/P751_compressed.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/kem/sike/P751/P751_compressed.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/common/common.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/common/common.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/common/rand.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/common/rand.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/common/rand_nist.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/common/rand_nist.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/crypto/aes/aes_c.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/crypto/aes/aes_c.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/crypto/sha2/sha2_c.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/crypto/sha2/sha2_c.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/crypto/sha3/sha3_c.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/crypto/sha3/sha3_c.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/crypto/sha3/sha3x4.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/crypto/sha3/sha3x4.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/kem/kem.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/kem/kem.c

echo "gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/sig/sig.c"
gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wstrict-prototypes -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/home/kealan/Downloads/liboqs/include -I.  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -D_GENERIC_ -D_AMD64_ -w -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -maes -c  -I./include ./src/sig/sig.c

echo "ar rc liboqs.a aes_c.o kem.o P751.o rand.o sha3_c.o sig.o common.o P751_compressed.o rand_nist.o sha2_c.o sha3x4.o kem_sike.o"
ar rc liboqs.a aes_c.o kem.o P751.o rand.o sha3_c.o sig.o common.o P751_compressed.o rand_nist.o sha2_c.o sha3x4.o kem_sike.o

