// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assets.proto

package protobuffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PBAssetType int32

const (
	PBAssetType_wallet  PBAssetType = 0
	PBAssetType_trustee PBAssetType = 1
	PBAssetType_iddoc   PBAssetType = 2
)

var PBAssetType_name = map[int32]string{
	0: "wallet",
	1: "trustee",
	2: "iddoc",
}

var PBAssetType_value = map[string]int32{
	"wallet":  0,
	"trustee": 1,
	"iddoc":   2,
}

func (x PBAssetType) String() string {
	return proto.EnumName(PBAssetType_name, int32(x))
}

func (PBAssetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{0}
}

type PBTransferType int32

const (
	PBTransferType_unspecified  PBTransferType = 0
	PBTransferType_settlePush   PBTransferType = 1
	PBTransferType_settlePull   PBTransferType = 2
	PBTransferType_transferPush PBTransferType = 3
	PBTransferType_transferPull PBTransferType = 4
	PBTransferType_swap         PBTransferType = 5
	PBTransferType_load         PBTransferType = 6
)

var PBTransferType_name = map[int32]string{
	0: "unspecified",
	1: "settlePush",
	2: "settlePull",
	3: "transferPush",
	4: "transferPull",
	5: "swap",
	6: "load",
}

var PBTransferType_value = map[string]int32{
	"unspecified":  0,
	"settlePush":   1,
	"settlePull":   2,
	"transferPush": 3,
	"transferPull": 4,
	"swap":         5,
	"load":         6,
}

func (x PBTransferType) String() string {
	return proto.EnumName(PBTransferType_name, int32(x))
}

func (PBTransferType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{1}
}

type PBSignedAsset struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Signers              [][]byte `protobuf:"bytes,2,rep,name=Signers,proto3" json:"Signers,omitempty"`
	Asset                *PBAsset `protobuf:"bytes,3,opt,name=Asset,proto3" json:"Asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBSignedAsset) Reset()         { *m = PBSignedAsset{} }
func (m *PBSignedAsset) String() string { return proto.CompactTextString(m) }
func (*PBSignedAsset) ProtoMessage()    {}
func (*PBSignedAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{0}
}

func (m *PBSignedAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBSignedAsset.Unmarshal(m, b)
}
func (m *PBSignedAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBSignedAsset.Marshal(b, m, deterministic)
}
func (m *PBSignedAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBSignedAsset.Merge(m, src)
}
func (m *PBSignedAsset) XXX_Size() int {
	return xxx_messageInfo_PBSignedAsset.Size(m)
}
func (m *PBSignedAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_PBSignedAsset.DiscardUnknown(m)
}

var xxx_messageInfo_PBSignedAsset proto.InternalMessageInfo

func (m *PBSignedAsset) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *PBSignedAsset) GetSigners() [][]byte {
	if m != nil {
		return m.Signers
	}
	return nil
}

func (m *PBSignedAsset) GetAsset() *PBAsset {
	if m != nil {
		return m.Asset
	}
	return nil
}

type PBAsset struct {
	Type  PBAssetType `protobuf:"varint,1,opt,name=Type,proto3,enum=protobuffer.PBAssetType" json:"Type,omitempty"`
	ID    []byte      `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner []byte      `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	// Types that are valid to be assigned to AssetDefinition:
	//	*PBAsset_Wallet
	//	*PBAsset_TrusteeGroup
	//	*PBAsset_Iddoc
	AssetDefinition      isPBAsset_AssetDefinition `protobuf_oneof:"AssetDefinition"`
	Transferlist         map[string]*PBTransfer    `protobuf:"bytes,8,rep,name=Transferlist,proto3" json:"Transferlist,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *PBAsset) Reset()         { *m = PBAsset{} }
func (m *PBAsset) String() string { return proto.CompactTextString(m) }
func (*PBAsset) ProtoMessage()    {}
func (*PBAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{1}
}

func (m *PBAsset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBAsset.Unmarshal(m, b)
}
func (m *PBAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBAsset.Marshal(b, m, deterministic)
}
func (m *PBAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBAsset.Merge(m, src)
}
func (m *PBAsset) XXX_Size() int {
	return xxx_messageInfo_PBAsset.Size(m)
}
func (m *PBAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_PBAsset.DiscardUnknown(m)
}

var xxx_messageInfo_PBAsset proto.InternalMessageInfo

func (m *PBAsset) GetType() PBAssetType {
	if m != nil {
		return m.Type
	}
	return PBAssetType_wallet
}

func (m *PBAsset) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *PBAsset) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

type isPBAsset_AssetDefinition interface {
	isPBAsset_AssetDefinition()
}

type PBAsset_Wallet struct {
	Wallet *PBWallet `protobuf:"bytes,4,opt,name=Wallet,proto3,oneof"`
}

type PBAsset_TrusteeGroup struct {
	TrusteeGroup *PBTrusteeGroup `protobuf:"bytes,5,opt,name=TrusteeGroup,proto3,oneof"`
}

type PBAsset_Iddoc struct {
	Iddoc *PBIDDoc `protobuf:"bytes,6,opt,name=Iddoc,proto3,oneof"`
}

func (*PBAsset_Wallet) isPBAsset_AssetDefinition() {}

func (*PBAsset_TrusteeGroup) isPBAsset_AssetDefinition() {}

func (*PBAsset_Iddoc) isPBAsset_AssetDefinition() {}

func (m *PBAsset) GetAssetDefinition() isPBAsset_AssetDefinition {
	if m != nil {
		return m.AssetDefinition
	}
	return nil
}

func (m *PBAsset) GetWallet() *PBWallet {
	if x, ok := m.GetAssetDefinition().(*PBAsset_Wallet); ok {
		return x.Wallet
	}
	return nil
}

func (m *PBAsset) GetTrusteeGroup() *PBTrusteeGroup {
	if x, ok := m.GetAssetDefinition().(*PBAsset_TrusteeGroup); ok {
		return x.TrusteeGroup
	}
	return nil
}

func (m *PBAsset) GetIddoc() *PBIDDoc {
	if x, ok := m.GetAssetDefinition().(*PBAsset_Iddoc); ok {
		return x.Iddoc
	}
	return nil
}

func (m *PBAsset) GetTransferlist() map[string]*PBTransfer {
	if m != nil {
		return m.Transferlist
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PBAsset) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PBAsset_Wallet)(nil),
		(*PBAsset_TrusteeGroup)(nil),
		(*PBAsset_Iddoc)(nil),
	}
}

type PBTransfer struct {
	Type                 PBTransferType    `protobuf:"varint,1,opt,name=Type,proto3,enum=protobuffer.PBTransferType" json:"Type,omitempty"`
	Expression           string            `protobuf:"bytes,2,opt,name=Expression,proto3" json:"Expression,omitempty"`
	Participants         map[string][]byte `protobuf:"bytes,3,rep,name=Participants,proto3" json:"Participants,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PBTransfer) Reset()         { *m = PBTransfer{} }
func (m *PBTransfer) String() string { return proto.CompactTextString(m) }
func (*PBTransfer) ProtoMessage()    {}
func (*PBTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{2}
}

func (m *PBTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBTransfer.Unmarshal(m, b)
}
func (m *PBTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBTransfer.Marshal(b, m, deterministic)
}
func (m *PBTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBTransfer.Merge(m, src)
}
func (m *PBTransfer) XXX_Size() int {
	return xxx_messageInfo_PBTransfer.Size(m)
}
func (m *PBTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_PBTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_PBTransfer proto.InternalMessageInfo

func (m *PBTransfer) GetType() PBTransferType {
	if m != nil {
		return m.Type
	}
	return PBTransferType_unspecified
}

func (m *PBTransfer) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *PBTransfer) GetParticipants() map[string][]byte {
	if m != nil {
		return m.Participants
	}
	return nil
}

//Asset Definitons
type PBWallet struct {
	Description          string   `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
	Principal            []byte   `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Creditor             []byte   `protobuf:"bytes,3,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Initiator            []byte   `protobuf:"bytes,4,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Address              []byte   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Counterparty         []byte   `protobuf:"bytes,6,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBWallet) Reset()         { *m = PBWallet{} }
func (m *PBWallet) String() string { return proto.CompactTextString(m) }
func (*PBWallet) ProtoMessage()    {}
func (*PBWallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{3}
}

func (m *PBWallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBWallet.Unmarshal(m, b)
}
func (m *PBWallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBWallet.Marshal(b, m, deterministic)
}
func (m *PBWallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBWallet.Merge(m, src)
}
func (m *PBWallet) XXX_Size() int {
	return xxx_messageInfo_PBWallet.Size(m)
}
func (m *PBWallet) XXX_DiscardUnknown() {
	xxx_messageInfo_PBWallet.DiscardUnknown(m)
}

var xxx_messageInfo_PBWallet proto.InternalMessageInfo

func (m *PBWallet) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PBWallet) GetPrincipal() []byte {
	if m != nil {
		return m.Principal
	}
	return nil
}

func (m *PBWallet) GetCreditor() []byte {
	if m != nil {
		return m.Creditor
	}
	return nil
}

func (m *PBWallet) GetInitiator() []byte {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *PBWallet) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *PBWallet) GetCounterparty() []byte {
	if m != nil {
		return m.Counterparty
	}
	return nil
}

type PBTrusteeGroup struct {
	TrusteeID            [][]byte `protobuf:"bytes,1,rep,name=TrusteeID,proto3" json:"TrusteeID,omitempty"`
	Threshold            int64    `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PBTrusteeGroup) Reset()         { *m = PBTrusteeGroup{} }
func (m *PBTrusteeGroup) String() string { return proto.CompactTextString(m) }
func (*PBTrusteeGroup) ProtoMessage()    {}
func (*PBTrusteeGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{4}
}

func (m *PBTrusteeGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBTrusteeGroup.Unmarshal(m, b)
}
func (m *PBTrusteeGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBTrusteeGroup.Marshal(b, m, deterministic)
}
func (m *PBTrusteeGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBTrusteeGroup.Merge(m, src)
}
func (m *PBTrusteeGroup) XXX_Size() int {
	return xxx_messageInfo_PBTrusteeGroup.Size(m)
}
func (m *PBTrusteeGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_PBTrusteeGroup.DiscardUnknown(m)
}

var xxx_messageInfo_PBTrusteeGroup proto.InternalMessageInfo

func (m *PBTrusteeGroup) GetTrusteeID() [][]byte {
	if m != nil {
		return m.TrusteeID
	}
	return nil
}

func (m *PBTrusteeGroup) GetThreshold() int64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

type PBIDDoc struct {
	AuthenticationReference string   `protobuf:"bytes,1,opt,name=AuthenticationReference,proto3" json:"AuthenticationReference,omitempty"`
	BeneficiaryECPublicKey  []byte   `protobuf:"bytes,2,opt,name=BeneficiaryECPublicKey,proto3" json:"BeneficiaryECPublicKey,omitempty"`
	SikePublicKey           []byte   `protobuf:"bytes,3,opt,name=SikePublicKey,proto3" json:"SikePublicKey,omitempty"`
	BLSPublicKey            []byte   `protobuf:"bytes,4,opt,name=BLSPublicKey,proto3" json:"BLSPublicKey,omitempty"`
	Timestamp               int64    `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *PBIDDoc) Reset()         { *m = PBIDDoc{} }
func (m *PBIDDoc) String() string { return proto.CompactTextString(m) }
func (*PBIDDoc) ProtoMessage()    {}
func (*PBIDDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{5}
}

func (m *PBIDDoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PBIDDoc.Unmarshal(m, b)
}
func (m *PBIDDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PBIDDoc.Marshal(b, m, deterministic)
}
func (m *PBIDDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PBIDDoc.Merge(m, src)
}
func (m *PBIDDoc) XXX_Size() int {
	return xxx_messageInfo_PBIDDoc.Size(m)
}
func (m *PBIDDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_PBIDDoc.DiscardUnknown(m)
}

var xxx_messageInfo_PBIDDoc proto.InternalMessageInfo

func (m *PBIDDoc) GetAuthenticationReference() string {
	if m != nil {
		return m.AuthenticationReference
	}
	return ""
}

func (m *PBIDDoc) GetBeneficiaryECPublicKey() []byte {
	if m != nil {
		return m.BeneficiaryECPublicKey
	}
	return nil
}

func (m *PBIDDoc) GetSikePublicKey() []byte {
	if m != nil {
		return m.SikePublicKey
	}
	return nil
}

func (m *PBIDDoc) GetBLSPublicKey() []byte {
	if m != nil {
		return m.BLSPublicKey
	}
	return nil
}

func (m *PBIDDoc) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuffer.PBAssetType", PBAssetType_name, PBAssetType_value)
	proto.RegisterEnum("protobuffer.PBTransferType", PBTransferType_name, PBTransferType_value)
	proto.RegisterType((*PBSignedAsset)(nil), "protobuffer.PBSignedAsset")
	proto.RegisterType((*PBAsset)(nil), "protobuffer.PBAsset")
	proto.RegisterMapType((map[string]*PBTransfer)(nil), "protobuffer.PBAsset.TransferlistEntry")
	proto.RegisterType((*PBTransfer)(nil), "protobuffer.PBTransfer")
	proto.RegisterMapType((map[string][]byte)(nil), "protobuffer.PBTransfer.ParticipantsEntry")
	proto.RegisterType((*PBWallet)(nil), "protobuffer.PBWallet")
	proto.RegisterType((*PBTrusteeGroup)(nil), "protobuffer.PBTrusteeGroup")
	proto.RegisterType((*PBIDDoc)(nil), "protobuffer.PBIDDoc")
}

func init() { proto.RegisterFile("assets.proto", fileDescriptor_610ca40ce07a87fe) }

var fileDescriptor_610ca40ce07a87fe = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xd1, 0x4e, 0xdb, 0x4a,
	0x10, 0x8d, 0xe3, 0x24, 0x24, 0x63, 0x13, 0xcc, 0x8a, 0x7b, 0xb1, 0xe0, 0xea, 0x2a, 0x8a, 0xae,
	0xae, 0x52, 0x44, 0x83, 0x9a, 0x4a, 0x15, 0xea, 0x4b, 0x45, 0x1a, 0x54, 0xd2, 0x52, 0x35, 0x5a,
	0x90, 0xda, 0x57, 0x63, 0x4f, 0x9a, 0x15, 0xc6, 0xb6, 0x76, 0xd7, 0xa5, 0xf9, 0xb3, 0x3e, 0xf7,
	0x57, 0xfa, 0xdc, 0x7f, 0xa8, 0x76, 0xed, 0x60, 0x1b, 0x92, 0xa7, 0x78, 0xce, 0x9c, 0x99, 0xd9,
	0x3d, 0x7b, 0x26, 0x60, 0x7b, 0x42, 0xa0, 0x14, 0xc3, 0x84, 0xc7, 0x32, 0x26, 0x96, 0xfe, 0xb9,
	0x49, 0xe7, 0x73, 0xe4, 0x7d, 0x01, 0xdb, 0xb3, 0xf1, 0x15, 0xfb, 0x1a, 0x61, 0x70, 0xa6, 0x48,
	0xe4, 0x1f, 0xe8, 0xa8, 0xd0, 0x93, 0x29, 0x47, 0xd7, 0xe8, 0x19, 0x03, 0x9b, 0x16, 0x00, 0x71,
	0x61, 0x4b, 0x93, 0xb9, 0x70, 0xeb, 0x3d, 0x73, 0x60, 0xd3, 0x55, 0x48, 0x8e, 0xa0, 0xa9, 0x1b,
	0xb8, 0x66, 0xcf, 0x18, 0x58, 0xa3, 0xbd, 0x61, 0x69, 0xca, 0x70, 0x36, 0xd6, 0x39, 0x9a, 0x51,
	0xfa, 0x3f, 0x4c, 0xd8, 0xca, 0x21, 0x72, 0x0c, 0x8d, 0xeb, 0x65, 0x92, 0x8d, 0xea, 0x8e, 0xdc,
	0x75, 0x65, 0x2a, 0x4f, 0x35, 0x8b, 0x74, 0xa1, 0x3e, 0x9d, 0xb8, 0x75, 0x7d, 0xac, 0xfa, 0x74,
	0x42, 0xf6, 0xa0, 0xf9, 0xe9, 0x3e, 0x42, 0xae, 0xa7, 0xda, 0x34, 0x0b, 0xc8, 0x09, 0xb4, 0x3e,
	0x7b, 0x61, 0x88, 0xd2, 0x6d, 0xe8, 0xc3, 0xfc, 0xf5, 0xa8, 0x6b, 0x96, 0xbc, 0xa8, 0xd1, 0x9c,
	0x46, 0xce, 0xc0, 0xbe, 0xe6, 0xa9, 0x90, 0x88, 0xef, 0x78, 0x9c, 0x26, 0x6e, 0x53, 0x97, 0x1d,
	0x3e, 0x2a, 0x2b, 0x53, 0x2e, 0x6a, 0xb4, 0x52, 0x42, 0x8e, 0xa1, 0x39, 0x0d, 0x82, 0xd8, 0x77,
	0x5b, 0x6b, 0xef, 0x3f, 0x9d, 0x4c, 0x62, 0xff, 0xa2, 0x46, 0x33, 0x12, 0x79, 0xaf, 0x06, 0x7a,
	0x91, 0x98, 0x23, 0x0f, 0x99, 0x90, 0x6e, 0xbb, 0x67, 0x0e, 0xac, 0xd1, 0xff, 0xeb, 0x6e, 0x3f,
	0x2c, 0x13, 0xcf, 0x23, 0xc9, 0x97, 0xb4, 0x52, 0x7b, 0xf0, 0x05, 0x76, 0x9f, 0x50, 0x88, 0x03,
	0xe6, 0x2d, 0x2e, 0xb5, 0xaa, 0x1d, 0xaa, 0x3e, 0xc9, 0x73, 0x68, 0x7e, 0xf3, 0xc2, 0x14, 0xb5,
	0x7a, 0xd6, 0x68, 0xff, 0xc9, 0xe5, 0xb2, 0x16, 0x34, 0x63, 0xbd, 0xae, 0x9f, 0x1a, 0xe3, 0x5d,
	0xd8, 0xd1, 0x47, 0x98, 0xe0, 0x9c, 0x45, 0x4c, 0xb2, 0x38, 0xea, 0xff, 0x36, 0x00, 0x0a, 0x32,
	0x39, 0xa9, 0xbc, 0xde, 0xe1, 0x86, 0x9e, 0xa5, 0x07, 0xfc, 0x17, 0xe0, 0xfc, 0x7b, 0xc2, 0x51,
	0x08, 0x16, 0x47, 0xfa, 0x28, 0x1d, 0x5a, 0x42, 0xc8, 0x47, 0xb0, 0x67, 0x1e, 0x97, 0xcc, 0x67,
	0x89, 0x17, 0x49, 0xe1, 0x9a, 0x5a, 0x98, 0x67, 0x1b, 0x1a, 0x0f, 0xcb, 0xdc, 0x5c, 0x9b, 0x32,
	0x74, 0xf0, 0x06, 0x76, 0x9f, 0x50, 0xd6, 0x68, 0xb3, 0x57, 0xd6, 0xc6, 0x2e, 0x49, 0xd0, 0xff,
	0x69, 0x40, 0x7b, 0x65, 0x18, 0xd2, 0x03, 0x6b, 0x82, 0xc2, 0xe7, 0x2c, 0x51, 0x5a, 0xe4, 0x0d,
	0xca, 0x90, 0xda, 0x9e, 0x84, 0xb3, 0x48, 0x8d, 0x0b, 0xf3, 0x66, 0x05, 0x40, 0x0e, 0xa0, 0xed,
	0x73, 0x0c, 0x98, 0x8c, 0x57, 0x86, 0x7d, 0x88, 0x55, 0xa5, 0xd6, 0xd8, 0x53, 0xc9, 0x46, 0x56,
	0xf9, 0x00, 0xa8, 0xbd, 0xf3, 0x82, 0x40, 0x89, 0xa4, 0xbd, 0x69, 0xd3, 0x55, 0x48, 0xfa, 0x60,
	0xfb, 0x71, 0x1a, 0x49, 0xe4, 0x89, 0xc7, 0xe5, 0x52, 0xdb, 0xcf, 0xa6, 0x15, 0xac, 0x7f, 0x09,
	0xdd, 0xaa, 0x7b, 0xd5, 0xb4, 0x3c, 0x9e, 0x4e, 0x5c, 0x43, 0x6f, 0x72, 0x01, 0xa8, 0xac, 0x5c,
	0x70, 0x14, 0x8b, 0x38, 0x0c, 0xf4, 0x2d, 0x4c, 0x5a, 0x00, 0xfd, 0x5f, 0x86, 0xda, 0x5e, 0x6d,
	0x68, 0x72, 0x0a, 0xfb, 0x67, 0xa9, 0x5c, 0x60, 0x24, 0x99, 0xef, 0x29, 0x05, 0x28, 0xce, 0x91,
	0x63, 0xe4, 0x63, 0xae, 0xce, 0xa6, 0x34, 0x79, 0x05, 0x7f, 0x8f, 0x31, 0xc2, 0x39, 0xf3, 0x99,
	0xc7, 0x97, 0xe7, 0x6f, 0x67, 0xe9, 0x4d, 0xc8, 0xfc, 0x0f, 0xb8, 0xcc, 0x65, 0xdb, 0x90, 0x25,
	0xff, 0xc1, 0xf6, 0x15, 0xbb, 0xc5, 0x82, 0x9e, 0x09, 0x59, 0x05, 0x95, 0x2a, 0xe3, 0xcb, 0xab,
	0x82, 0x94, 0x09, 0x5a, 0xc1, 0xb4, 0x06, 0xec, 0x0e, 0x85, 0xf4, 0xee, 0xb2, 0x8d, 0x37, 0x69,
	0x01, 0x1c, 0xbd, 0x00, 0xab, 0xf4, 0xf7, 0x43, 0x00, 0x5a, 0xf7, 0xda, 0x04, 0x4e, 0x8d, 0x58,
	0xb0, 0x25, 0x33, 0xad, 0x1c, 0x83, 0x74, 0xa0, 0xc9, 0xd4, 0x4a, 0x3b, 0xf5, 0xa3, 0x65, 0x26,
	0x73, 0xe1, 0x79, 0xb2, 0x03, 0x56, 0x1a, 0x89, 0x04, 0x7d, 0x36, 0x67, 0x18, 0x38, 0x35, 0xd2,
	0x05, 0x10, 0x28, 0x65, 0x88, 0xb3, 0x54, 0x2c, 0x1c, 0xa3, 0x1c, 0x87, 0xa1, 0x53, 0x27, 0x0e,
	0xd8, 0x32, 0x6f, 0xa0, 0x19, 0x66, 0x15, 0x09, 0x43, 0xa7, 0x41, 0xda, 0xd0, 0x10, 0xf7, 0x5e,
	0xe2, 0x34, 0xd5, 0x57, 0x18, 0x7b, 0x81, 0xd3, 0xba, 0x69, 0xe9, 0xfd, 0x78, 0xf9, 0x27, 0x00,
	0x00, 0xff, 0xff, 0x7c, 0xd5, 0x21, 0x71, 0xea, 0x05, 0x00, 0x00,
}
