// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assets.proto

package protobuffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AssetType int32

const (
	AssetType_wallet  AssetType = 0
	AssetType_trustee AssetType = 1
	AssetType_iddoc   AssetType = 2
)

var AssetType_name = map[int32]string{
	0: "wallet",
	1: "trustee",
	2: "iddoc",
}

var AssetType_value = map[string]int32{
	"wallet":  0,
	"trustee": 1,
	"iddoc":   2,
}

func (x AssetType) String() string {
	return proto.EnumName(AssetType_name, int32(x))
}

func (AssetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{0}
}

type TransferType int32

const (
	TransferType_unspecified  TransferType = 0
	TransferType_settlePush   TransferType = 1
	TransferType_settlePull   TransferType = 2
	TransferType_transferPush TransferType = 3
	TransferType_tranferPull  TransferType = 4
	TransferType_swap         TransferType = 5
	TransferType_load         TransferType = 6
)

var TransferType_name = map[int32]string{
	0: "unspecified",
	1: "settlePush",
	2: "settlePull",
	3: "transferPush",
	4: "tranferPull",
	5: "swap",
	6: "load",
}

var TransferType_value = map[string]int32{
	"unspecified":  0,
	"settlePush":   1,
	"settlePull":   2,
	"transferPush": 3,
	"tranferPull":  4,
	"swap":         5,
	"load":         6,
}

func (x TransferType) String() string {
	return proto.EnumName(TransferType_name, int32(x))
}

func (TransferType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{1}
}

type Signature struct {
	Signature []byte   `protobuf:"bytes,1,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Signers   [][]byte `protobuf:"bytes,2,rep,name=Signers,proto3" json:"Signers,omitempty"`
	// Types that are valid to be assigned to SignatureAsset:
	//	*Signature_Declaration
	//	*Signature_Update
	SignatureAsset       isSignature_SignatureAsset `protobuf_oneof:"SignatureAsset"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{0}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Signature) GetSigners() [][]byte {
	if m != nil {
		return m.Signers
	}
	return nil
}

type isSignature_SignatureAsset interface {
	isSignature_SignatureAsset()
}

type Signature_Declaration struct {
	Declaration *AssetDeclaration `protobuf:"bytes,3,opt,name=declaration,proto3,oneof"`
}

type Signature_Update struct {
	Update *AssetUpdate `protobuf:"bytes,4,opt,name=update,proto3,oneof"`
}

func (*Signature_Declaration) isSignature_SignatureAsset() {}

func (*Signature_Update) isSignature_SignatureAsset() {}

func (m *Signature) GetSignatureAsset() isSignature_SignatureAsset {
	if m != nil {
		return m.SignatureAsset
	}
	return nil
}

func (m *Signature) GetDeclaration() *AssetDeclaration {
	if x, ok := m.GetSignatureAsset().(*Signature_Declaration); ok {
		return x.Declaration
	}
	return nil
}

func (m *Signature) GetUpdate() *AssetUpdate {
	if x, ok := m.GetSignatureAsset().(*Signature_Update); ok {
		return x.Update
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Signature) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Signature_Declaration)(nil),
		(*Signature_Update)(nil),
	}
}

type AssetDeclaration struct {
	Type  AssetType `protobuf:"varint,1,opt,name=Type,proto3,enum=protobuffer.AssetType" json:"Type,omitempty"`
	ID    []byte    `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner []byte    `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	// Types that are valid to be assigned to AssetDefinition:
	//	*AssetDeclaration_Wallet
	//	*AssetDeclaration_TrusteeGroup
	//	*AssetDeclaration_Iddoc
	AssetDefinition      isAssetDeclaration_AssetDefinition `protobuf_oneof:"AssetDefinition"`
	Transferlist         []*Transfer                        `protobuf:"bytes,7,rep,name=Transferlist,proto3" json:"Transferlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *AssetDeclaration) Reset()         { *m = AssetDeclaration{} }
func (m *AssetDeclaration) String() string { return proto.CompactTextString(m) }
func (*AssetDeclaration) ProtoMessage()    {}
func (*AssetDeclaration) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{1}
}

func (m *AssetDeclaration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetDeclaration.Unmarshal(m, b)
}
func (m *AssetDeclaration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetDeclaration.Marshal(b, m, deterministic)
}
func (m *AssetDeclaration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetDeclaration.Merge(m, src)
}
func (m *AssetDeclaration) XXX_Size() int {
	return xxx_messageInfo_AssetDeclaration.Size(m)
}
func (m *AssetDeclaration) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetDeclaration.DiscardUnknown(m)
}

var xxx_messageInfo_AssetDeclaration proto.InternalMessageInfo

func (m *AssetDeclaration) GetType() AssetType {
	if m != nil {
		return m.Type
	}
	return AssetType_wallet
}

func (m *AssetDeclaration) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *AssetDeclaration) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

type isAssetDeclaration_AssetDefinition interface {
	isAssetDeclaration_AssetDefinition()
}

type AssetDeclaration_Wallet struct {
	Wallet *Wallet `protobuf:"bytes,4,opt,name=Wallet,proto3,oneof"`
}

type AssetDeclaration_TrusteeGroup struct {
	TrusteeGroup *TrusteeGroup `protobuf:"bytes,5,opt,name=TrusteeGroup,proto3,oneof"`
}

type AssetDeclaration_Iddoc struct {
	Iddoc *IDDoc `protobuf:"bytes,6,opt,name=Iddoc,proto3,oneof"`
}

func (*AssetDeclaration_Wallet) isAssetDeclaration_AssetDefinition() {}

func (*AssetDeclaration_TrusteeGroup) isAssetDeclaration_AssetDefinition() {}

func (*AssetDeclaration_Iddoc) isAssetDeclaration_AssetDefinition() {}

func (m *AssetDeclaration) GetAssetDefinition() isAssetDeclaration_AssetDefinition {
	if m != nil {
		return m.AssetDefinition
	}
	return nil
}

func (m *AssetDeclaration) GetWallet() *Wallet {
	if x, ok := m.GetAssetDefinition().(*AssetDeclaration_Wallet); ok {
		return x.Wallet
	}
	return nil
}

func (m *AssetDeclaration) GetTrusteeGroup() *TrusteeGroup {
	if x, ok := m.GetAssetDefinition().(*AssetDeclaration_TrusteeGroup); ok {
		return x.TrusteeGroup
	}
	return nil
}

func (m *AssetDeclaration) GetIddoc() *IDDoc {
	if x, ok := m.GetAssetDefinition().(*AssetDeclaration_Iddoc); ok {
		return x.Iddoc
	}
	return nil
}

func (m *AssetDeclaration) GetTransferlist() []*Transfer {
	if m != nil {
		return m.Transferlist
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AssetDeclaration) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AssetDeclaration_Wallet)(nil),
		(*AssetDeclaration_TrusteeGroup)(nil),
		(*AssetDeclaration_Iddoc)(nil),
	}
}

//A subsequent message to update the status of an asset.
type AssetUpdate struct {
	Type     AssetType `protobuf:"varint,1,opt,name=Type,proto3,enum=protobuffer.AssetType" json:"Type,omitempty"`
	ID       []byte    `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	NewOwner []byte    `protobuf:"bytes,3,opt,name=NewOwner,proto3" json:"NewOwner,omitempty"`
	// Types that are valid to be assigned to AssetDefinition:
	//	*AssetUpdate_Wallet
	//	*AssetUpdate_TrusteeGroup
	//	*AssetUpdate_Iddoc
	AssetDefinition      isAssetUpdate_AssetDefinition `protobuf_oneof:"AssetDefinition"`
	Transferlist         []*Transfer                   `protobuf:"bytes,7,rep,name=Transferlist,proto3" json:"Transferlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *AssetUpdate) Reset()         { *m = AssetUpdate{} }
func (m *AssetUpdate) String() string { return proto.CompactTextString(m) }
func (*AssetUpdate) ProtoMessage()    {}
func (*AssetUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{2}
}

func (m *AssetUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetUpdate.Unmarshal(m, b)
}
func (m *AssetUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetUpdate.Marshal(b, m, deterministic)
}
func (m *AssetUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetUpdate.Merge(m, src)
}
func (m *AssetUpdate) XXX_Size() int {
	return xxx_messageInfo_AssetUpdate.Size(m)
}
func (m *AssetUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_AssetUpdate proto.InternalMessageInfo

func (m *AssetUpdate) GetType() AssetType {
	if m != nil {
		return m.Type
	}
	return AssetType_wallet
}

func (m *AssetUpdate) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *AssetUpdate) GetNewOwner() []byte {
	if m != nil {
		return m.NewOwner
	}
	return nil
}

type isAssetUpdate_AssetDefinition interface {
	isAssetUpdate_AssetDefinition()
}

type AssetUpdate_Wallet struct {
	Wallet *Wallet `protobuf:"bytes,4,opt,name=Wallet,proto3,oneof"`
}

type AssetUpdate_TrusteeGroup struct {
	TrusteeGroup *TrusteeGroup `protobuf:"bytes,5,opt,name=TrusteeGroup,proto3,oneof"`
}

type AssetUpdate_Iddoc struct {
	Iddoc *IDDoc `protobuf:"bytes,6,opt,name=Iddoc,proto3,oneof"`
}

func (*AssetUpdate_Wallet) isAssetUpdate_AssetDefinition() {}

func (*AssetUpdate_TrusteeGroup) isAssetUpdate_AssetDefinition() {}

func (*AssetUpdate_Iddoc) isAssetUpdate_AssetDefinition() {}

func (m *AssetUpdate) GetAssetDefinition() isAssetUpdate_AssetDefinition {
	if m != nil {
		return m.AssetDefinition
	}
	return nil
}

func (m *AssetUpdate) GetWallet() *Wallet {
	if x, ok := m.GetAssetDefinition().(*AssetUpdate_Wallet); ok {
		return x.Wallet
	}
	return nil
}

func (m *AssetUpdate) GetTrusteeGroup() *TrusteeGroup {
	if x, ok := m.GetAssetDefinition().(*AssetUpdate_TrusteeGroup); ok {
		return x.TrusteeGroup
	}
	return nil
}

func (m *AssetUpdate) GetIddoc() *IDDoc {
	if x, ok := m.GetAssetDefinition().(*AssetUpdate_Iddoc); ok {
		return x.Iddoc
	}
	return nil
}

func (m *AssetUpdate) GetTransferlist() []*Transfer {
	if m != nil {
		return m.Transferlist
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*AssetUpdate) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*AssetUpdate_Wallet)(nil),
		(*AssetUpdate_TrusteeGroup)(nil),
		(*AssetUpdate_Iddoc)(nil),
	}
}

type Transfer struct {
	Type                 TransferType      `protobuf:"varint,1,opt,name=Type,proto3,enum=protobuffer.TransferType" json:"Type,omitempty"`
	Expression           string            `protobuf:"bytes,2,opt,name=Expression,proto3" json:"Expression,omitempty"`
	Participants         map[string][]byte `protobuf:"bytes,3,rep,name=Participants,proto3" json:"Participants,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{3}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetType() TransferType {
	if m != nil {
		return m.Type
	}
	return TransferType_unspecified
}

func (m *Transfer) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *Transfer) GetParticipants() map[string][]byte {
	if m != nil {
		return m.Participants
	}
	return nil
}

//Asset Definitons
type Wallet struct {
	Description          string   `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
	Principal            []byte   `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Creditor             []byte   `protobuf:"bytes,3,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Initiator            []byte   `protobuf:"bytes,4,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Address              []byte   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Counterparty         []byte   `protobuf:"bytes,6,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wallet) Reset()         { *m = Wallet{} }
func (m *Wallet) String() string { return proto.CompactTextString(m) }
func (*Wallet) ProtoMessage()    {}
func (*Wallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{4}
}

func (m *Wallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wallet.Unmarshal(m, b)
}
func (m *Wallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wallet.Marshal(b, m, deterministic)
}
func (m *Wallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallet.Merge(m, src)
}
func (m *Wallet) XXX_Size() int {
	return xxx_messageInfo_Wallet.Size(m)
}
func (m *Wallet) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallet.DiscardUnknown(m)
}

var xxx_messageInfo_Wallet proto.InternalMessageInfo

func (m *Wallet) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Wallet) GetPrincipal() []byte {
	if m != nil {
		return m.Principal
	}
	return nil
}

func (m *Wallet) GetCreditor() []byte {
	if m != nil {
		return m.Creditor
	}
	return nil
}

func (m *Wallet) GetInitiator() []byte {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *Wallet) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Wallet) GetCounterparty() []byte {
	if m != nil {
		return m.Counterparty
	}
	return nil
}

type TrusteeGroup struct {
	TrusteeID            [][]byte `protobuf:"bytes,1,rep,name=TrusteeID,proto3" json:"TrusteeID,omitempty"`
	Threshold            int64    `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrusteeGroup) Reset()         { *m = TrusteeGroup{} }
func (m *TrusteeGroup) String() string { return proto.CompactTextString(m) }
func (*TrusteeGroup) ProtoMessage()    {}
func (*TrusteeGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{5}
}

func (m *TrusteeGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrusteeGroup.Unmarshal(m, b)
}
func (m *TrusteeGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrusteeGroup.Marshal(b, m, deterministic)
}
func (m *TrusteeGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrusteeGroup.Merge(m, src)
}
func (m *TrusteeGroup) XXX_Size() int {
	return xxx_messageInfo_TrusteeGroup.Size(m)
}
func (m *TrusteeGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_TrusteeGroup.DiscardUnknown(m)
}

var xxx_messageInfo_TrusteeGroup proto.InternalMessageInfo

func (m *TrusteeGroup) GetTrusteeID() [][]byte {
	if m != nil {
		return m.TrusteeID
	}
	return nil
}

func (m *TrusteeGroup) GetThreshold() int64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

type IDDoc struct {
	AuthenticationReference string   `protobuf:"bytes,1,opt,name=AuthenticationReference,proto3" json:"AuthenticationReference,omitempty"`
	BeneficiaryECPublicKey  []byte   `protobuf:"bytes,2,opt,name=BeneficiaryECPublicKey,proto3" json:"BeneficiaryECPublicKey,omitempty"`
	SikePublicKey           []byte   `protobuf:"bytes,3,opt,name=SikePublicKey,proto3" json:"SikePublicKey,omitempty"`
	BLSPublicKey            []byte   `protobuf:"bytes,4,opt,name=BLSPublicKey,proto3" json:"BLSPublicKey,omitempty"`
	Timestamp               int64    `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *IDDoc) Reset()         { *m = IDDoc{} }
func (m *IDDoc) String() string { return proto.CompactTextString(m) }
func (*IDDoc) ProtoMessage()    {}
func (*IDDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{6}
}

func (m *IDDoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDDoc.Unmarshal(m, b)
}
func (m *IDDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDDoc.Marshal(b, m, deterministic)
}
func (m *IDDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDDoc.Merge(m, src)
}
func (m *IDDoc) XXX_Size() int {
	return xxx_messageInfo_IDDoc.Size(m)
}
func (m *IDDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_IDDoc.DiscardUnknown(m)
}

var xxx_messageInfo_IDDoc proto.InternalMessageInfo

func (m *IDDoc) GetAuthenticationReference() string {
	if m != nil {
		return m.AuthenticationReference
	}
	return ""
}

func (m *IDDoc) GetBeneficiaryECPublicKey() []byte {
	if m != nil {
		return m.BeneficiaryECPublicKey
	}
	return nil
}

func (m *IDDoc) GetSikePublicKey() []byte {
	if m != nil {
		return m.SikePublicKey
	}
	return nil
}

func (m *IDDoc) GetBLSPublicKey() []byte {
	if m != nil {
		return m.BLSPublicKey
	}
	return nil
}

func (m *IDDoc) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuffer.AssetType", AssetType_name, AssetType_value)
	proto.RegisterEnum("protobuffer.TransferType", TransferType_name, TransferType_value)
	proto.RegisterType((*Signature)(nil), "protobuffer.Signature")
	proto.RegisterType((*AssetDeclaration)(nil), "protobuffer.AssetDeclaration")
	proto.RegisterType((*AssetUpdate)(nil), "protobuffer.AssetUpdate")
	proto.RegisterType((*Transfer)(nil), "protobuffer.Transfer")
	proto.RegisterMapType((map[string][]byte)(nil), "protobuffer.Transfer.ParticipantsEntry")
	proto.RegisterType((*Wallet)(nil), "protobuffer.Wallet")
	proto.RegisterType((*TrusteeGroup)(nil), "protobuffer.TrusteeGroup")
	proto.RegisterType((*IDDoc)(nil), "protobuffer.IDDoc")
}

func init() { proto.RegisterFile("assets.proto", fileDescriptor_610ca40ce07a87fe) }

var fileDescriptor_610ca40ce07a87fe = []byte{
	// 741 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x54, 0xdf, 0x6e, 0xfb, 0x34,
	0x14, 0x6e, 0x92, 0xb6, 0x5b, 0x4f, 0x42, 0x7f, 0x99, 0x81, 0x91, 0x4d, 0x80, 0xaa, 0x0a, 0x89,
	0xaa, 0xd2, 0x8a, 0x54, 0x24, 0x34, 0xb8, 0x99, 0x56, 0x3a, 0xd1, 0x32, 0x04, 0x93, 0x37, 0xc4,
	0xb5, 0x97, 0x9c, 0x52, 0x6b, 0x59, 0x12, 0xd9, 0xce, 0x4a, 0xdf, 0x8e, 0x07, 0x40, 0xf0, 0x0c,
	0x5c, 0xf1, 0x1a, 0xc8, 0x4e, 0xda, 0x24, 0xfb, 0x73, 0xc5, 0x25, 0x57, 0xc9, 0xf9, 0xce, 0xf7,
	0x1d, 0xdb, 0x9f, 0x7d, 0x0e, 0x78, 0x4c, 0x4a, 0x54, 0x72, 0x92, 0x89, 0x54, 0xa5, 0xc4, 0x35,
	0x9f, 0xfb, 0x7c, 0xb5, 0x42, 0x31, 0xfc, 0xc3, 0x82, 0xde, 0x2d, 0xff, 0x35, 0x61, 0x2a, 0x17,
	0x48, 0x3e, 0xae, 0x05, 0x81, 0x35, 0xb0, 0x46, 0x1e, 0xad, 0x65, 0x03, 0x38, 0xd0, 0x01, 0x0a,
	0x19, 0xd8, 0x03, 0x67, 0xe4, 0xd1, 0x5d, 0x48, 0x2e, 0xc1, 0x8d, 0x30, 0x8c, 0x99, 0x60, 0x8a,
	0xa7, 0x49, 0xe0, 0x0c, 0xac, 0x91, 0x3b, 0xfd, 0x64, 0x52, 0x5b, 0x68, 0x72, 0xa9, 0xb7, 0x30,
	0xaf, 0x48, 0x8b, 0x16, 0xad, 0x6b, 0xc8, 0x14, 0xba, 0x79, 0x16, 0x31, 0x85, 0x41, 0xdb, 0xa8,
	0x83, 0x97, 0xea, 0x9f, 0x4d, 0x7e, 0xd1, 0xa2, 0x25, 0x73, 0xe6, 0x43, 0x7f, 0xbf, 0x3b, 0xc3,
	0x18, 0xfe, 0x69, 0x83, 0xff, 0x7c, 0x25, 0x32, 0x86, 0xf6, 0xdd, 0x36, 0x2b, 0x0e, 0xd4, 0x9f,
	0x1e, 0xbf, 0x2c, 0xac, 0xb3, 0xd4, 0x70, 0x48, 0x1f, 0xec, 0xe5, 0x3c, 0xb0, 0xcd, 0xd1, 0xed,
	0xe5, 0x9c, 0x7c, 0x00, 0x9d, 0x9f, 0x36, 0x09, 0x0a, 0x73, 0x26, 0x8f, 0x16, 0x01, 0x39, 0x83,
	0xee, 0x2f, 0x2c, 0x8e, 0x51, 0x95, 0x9b, 0x7d, 0xbf, 0x51, 0xb3, 0x48, 0xe9, 0x7d, 0x16, 0x7f,
	0xe4, 0x02, 0xbc, 0x3b, 0x91, 0x4b, 0x85, 0xf8, 0x9d, 0x48, 0xf3, 0x2c, 0xe8, 0x18, 0xd1, 0x49,
	0x43, 0x54, 0x27, 0x2c, 0x5a, 0xb4, 0x21, 0x20, 0x63, 0xe8, 0x2c, 0xa3, 0x28, 0x0d, 0x83, 0xae,
	0x51, 0x92, 0x86, 0x72, 0x39, 0x9f, 0xa7, 0xe1, 0xa2, 0x45, 0x0b, 0x0a, 0xf9, 0x5a, 0x2f, 0xc6,
	0x12, 0xb9, 0x42, 0x11, 0x73, 0xa9, 0x82, 0x83, 0x81, 0x33, 0x72, 0xa7, 0x1f, 0x3e, 0x5b, 0xac,
	0x20, 0xd0, 0x06, 0x75, 0x76, 0x04, 0xef, 0x4a, 0xf3, 0x56, 0x3c, 0xe1, 0xda, 0xbb, 0xe1, 0x5f,
	0x36, 0xb8, 0x35, 0xf3, 0xff, 0x93, 0x97, 0xa7, 0x70, 0xf8, 0x23, 0x6e, 0xea, 0x76, 0xee, 0xe3,
	0xff, 0x91, 0xa3, 0xff, 0x58, 0x70, 0xb8, 0xe3, 0x90, 0xb3, 0x86, 0x9d, 0x27, 0xaf, 0x96, 0xac,
	0x39, 0xfa, 0x29, 0xc0, 0xd5, 0x6f, 0x99, 0x40, 0x29, 0x75, 0x9b, 0x69, 0x67, 0x7b, 0xb4, 0x86,
	0x90, 0x6b, 0xf0, 0x6e, 0x98, 0x50, 0x3c, 0xe4, 0x19, 0x4b, 0x94, 0x0c, 0x1c, 0xb3, 0xd3, 0xcf,
	0x5f, 0x2d, 0x3b, 0xa9, 0x33, 0xaf, 0x12, 0x25, 0xb6, 0xb4, 0x21, 0x3e, 0xbd, 0x80, 0xa3, 0x17,
	0x14, 0xe2, 0x83, 0xf3, 0x80, 0x5b, 0xb3, 0xdf, 0x1e, 0xd5, 0xbf, 0xba, 0x43, 0x9e, 0x58, 0x9c,
	0x63, 0x79, 0xd1, 0x45, 0xf0, 0x8d, 0x7d, 0x6e, 0x0d, 0x7f, 0xb7, 0x76, 0x97, 0x4a, 0x06, 0xe0,
	0xce, 0x51, 0x86, 0x82, 0x67, 0x66, 0x40, 0x14, 0xf2, 0x3a, 0xa4, 0x47, 0x4f, 0x26, 0x78, 0xa2,
	0x17, 0x8b, 0xcb, 0x52, 0x15, 0xa0, 0x9f, 0x4e, 0x28, 0x30, 0xe2, 0x2a, 0xdd, 0x3f, 0x9d, 0x5d,
	0xac, 0x95, 0xc6, 0x5b, 0xa6, 0x93, 0xed, 0x42, 0xb9, 0x07, 0xf4, 0xd0, 0x62, 0x51, 0xa4, 0x0d,
	0x32, 0x8f, 0xc4, 0xa3, 0xbb, 0x90, 0x0c, 0xc1, 0x0b, 0xd3, 0x3c, 0x51, 0x28, 0x32, 0x26, 0xd4,
	0xd6, 0xbc, 0x04, 0x8f, 0x36, 0xb0, 0xe1, 0xf7, 0xcd, 0x77, 0xa6, 0xd7, 0x2a, 0xe3, 0xe5, 0x3c,
	0xb0, 0xcc, 0x10, 0xac, 0x00, 0x9d, 0x55, 0x6b, 0x81, 0x72, 0x9d, 0xc6, 0x91, 0x39, 0x83, 0x43,
	0x2b, 0x60, 0xf8, 0xb7, 0x05, 0x1d, 0xf3, 0xb2, 0xc8, 0x39, 0x7c, 0x74, 0x99, 0xab, 0x35, 0x26,
	0x8a, 0x87, 0x66, 0x44, 0x51, 0x5c, 0xa1, 0xc0, 0x24, 0xc4, 0xd2, 0x99, 0xb7, 0xd2, 0xe4, 0x2b,
	0x38, 0x9e, 0x61, 0x82, 0x2b, 0x1e, 0x72, 0x26, 0xb6, 0x57, 0xdf, 0xde, 0xe4, 0xf7, 0x31, 0x0f,
	0xaf, 0x71, 0x5b, 0x5a, 0xf6, 0x46, 0x96, 0x7c, 0x06, 0xef, 0xdd, 0xf2, 0x07, 0xac, 0xe8, 0x85,
	0x89, 0x4d, 0x50, 0x3b, 0x32, 0xfb, 0xe1, 0xb6, 0x22, 0x15, 0x66, 0x36, 0x30, 0xe3, 0x00, 0x7f,
	0x44, 0xa9, 0xd8, 0x63, 0xd1, 0x76, 0x0e, 0xad, 0x80, 0xf1, 0x17, 0xd0, 0xdb, 0x4f, 0x01, 0x02,
	0xd0, 0xdd, 0x98, 0xeb, 0xf7, 0x5b, 0xc4, 0x85, 0x03, 0x55, 0xf8, 0xe4, 0x5b, 0xa4, 0x07, 0x1d,
	0xae, 0x3b, 0xcb, 0xb7, 0xc7, 0x4f, 0x55, 0x6f, 0x19, 0xcd, 0x3b, 0x70, 0xf3, 0x44, 0x66, 0x18,
	0xf2, 0x15, 0xc7, 0xc8, 0x6f, 0x91, 0x3e, 0x80, 0x44, 0xa5, 0x62, 0xbc, 0xc9, 0xe5, 0xda, 0xb7,
	0xea, 0x71, 0x1c, 0xfb, 0x36, 0xf1, 0xc1, 0x53, 0x65, 0x01, 0xc3, 0x70, 0x74, 0x09, 0x8d, 0x18,
	0x20, 0x8e, 0xfd, 0x36, 0x39, 0x84, 0xb6, 0xdc, 0xb0, 0xcc, 0xef, 0xe8, 0xbf, 0x38, 0x65, 0x91,
	0xdf, 0xbd, 0xef, 0x9a, 0x96, 0xf8, 0xf2, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x51, 0x85,
	0x3f, 0x1b, 0x07, 0x00, 0x00,
}
