// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assets.proto

package protobuffer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AssetType int32

const (
	AssetType_wallet  AssetType = 0
	AssetType_trustee AssetType = 1
	AssetType_iddoc   AssetType = 2
)

var AssetType_name = map[int32]string{
	0: "wallet",
	1: "trustee",
	2: "iddoc",
}

var AssetType_value = map[string]int32{
	"wallet":  0,
	"trustee": 1,
	"iddoc":   2,
}

func (x AssetType) String() string {
	return proto.EnumName(AssetType_name, int32(x))
}

func (AssetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{0}
}

type TransferType int32

const (
	TransferType_unspecified  TransferType = 0
	TransferType_settlePush   TransferType = 1
	TransferType_settlePull   TransferType = 2
	TransferType_transferPush TransferType = 3
	TransferType_tranferPull  TransferType = 4
	TransferType_swap         TransferType = 5
	TransferType_load         TransferType = 6
)

var TransferType_name = map[int32]string{
	0: "unspecified",
	1: "settlePush",
	2: "settlePull",
	3: "transferPush",
	4: "tranferPull",
	5: "swap",
	6: "load",
}

var TransferType_value = map[string]int32{
	"unspecified":  0,
	"settlePush":   1,
	"settlePull":   2,
	"transferPush": 3,
	"tranferPull":  4,
	"swap":         5,
	"load":         6,
}

func (x TransferType) String() string {
	return proto.EnumName(TransferType_name, int32(x))
}

func (TransferType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{1}
}

type Signature struct {
	Signature            []byte   `protobuf:"bytes,1,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Signers              [][]byte `protobuf:"bytes,2,rep,name=Signers,proto3" json:"Signers,omitempty"`
	Asset                *Asset   `protobuf:"bytes,3,opt,name=Asset,proto3" json:"Asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{0}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Signature) GetSigners() [][]byte {
	if m != nil {
		return m.Signers
	}
	return nil
}

func (m *Signature) GetAsset() *Asset {
	if m != nil {
		return m.Asset
	}
	return nil
}

type Asset struct {
	Type  AssetType `protobuf:"varint,1,opt,name=Type,proto3,enum=protobuffer.AssetType" json:"Type,omitempty"`
	ID    []byte    `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner []byte    `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	// Types that are valid to be assigned to AssetDefinition:
	//	*Asset_Wallet
	//	*Asset_TrusteeGroup
	//	*Asset_Iddoc
	AssetDefinition      isAsset_AssetDefinition `protobuf_oneof:"AssetDefinition"`
	Transferlist         []*Transfer             `protobuf:"bytes,7,rep,name=Transferlist,proto3" json:"Transferlist,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Asset) Reset()         { *m = Asset{} }
func (m *Asset) String() string { return proto.CompactTextString(m) }
func (*Asset) ProtoMessage()    {}
func (*Asset) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{1}
}

func (m *Asset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Asset.Unmarshal(m, b)
}
func (m *Asset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Asset.Marshal(b, m, deterministic)
}
func (m *Asset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Asset.Merge(m, src)
}
func (m *Asset) XXX_Size() int {
	return xxx_messageInfo_Asset.Size(m)
}
func (m *Asset) XXX_DiscardUnknown() {
	xxx_messageInfo_Asset.DiscardUnknown(m)
}

var xxx_messageInfo_Asset proto.InternalMessageInfo

func (m *Asset) GetType() AssetType {
	if m != nil {
		return m.Type
	}
	return AssetType_wallet
}

func (m *Asset) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Asset) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

type isAsset_AssetDefinition interface {
	isAsset_AssetDefinition()
}

type Asset_Wallet struct {
	Wallet *Wallet `protobuf:"bytes,4,opt,name=Wallet,proto3,oneof"`
}

type Asset_TrusteeGroup struct {
	TrusteeGroup *TrusteeGroup `protobuf:"bytes,5,opt,name=TrusteeGroup,proto3,oneof"`
}

type Asset_Iddoc struct {
	Iddoc *IDDoc `protobuf:"bytes,6,opt,name=Iddoc,proto3,oneof"`
}

func (*Asset_Wallet) isAsset_AssetDefinition() {}

func (*Asset_TrusteeGroup) isAsset_AssetDefinition() {}

func (*Asset_Iddoc) isAsset_AssetDefinition() {}

func (m *Asset) GetAssetDefinition() isAsset_AssetDefinition {
	if m != nil {
		return m.AssetDefinition
	}
	return nil
}

func (m *Asset) GetWallet() *Wallet {
	if x, ok := m.GetAssetDefinition().(*Asset_Wallet); ok {
		return x.Wallet
	}
	return nil
}

func (m *Asset) GetTrusteeGroup() *TrusteeGroup {
	if x, ok := m.GetAssetDefinition().(*Asset_TrusteeGroup); ok {
		return x.TrusteeGroup
	}
	return nil
}

func (m *Asset) GetIddoc() *IDDoc {
	if x, ok := m.GetAssetDefinition().(*Asset_Iddoc); ok {
		return x.Iddoc
	}
	return nil
}

func (m *Asset) GetTransferlist() []*Transfer {
	if m != nil {
		return m.Transferlist
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Asset) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Asset_Wallet)(nil),
		(*Asset_TrusteeGroup)(nil),
		(*Asset_Iddoc)(nil),
	}
}

type Transfer struct {
	Type                 TransferType      `protobuf:"varint,1,opt,name=Type,proto3,enum=protobuffer.TransferType" json:"Type,omitempty"`
	Expression           string            `protobuf:"bytes,2,opt,name=Expression,proto3" json:"Expression,omitempty"`
	Participants         map[string][]byte `protobuf:"bytes,3,rep,name=Participants,proto3" json:"Participants,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Transfer) Reset()         { *m = Transfer{} }
func (m *Transfer) String() string { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()    {}
func (*Transfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{2}
}

func (m *Transfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transfer.Unmarshal(m, b)
}
func (m *Transfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transfer.Marshal(b, m, deterministic)
}
func (m *Transfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transfer.Merge(m, src)
}
func (m *Transfer) XXX_Size() int {
	return xxx_messageInfo_Transfer.Size(m)
}
func (m *Transfer) XXX_DiscardUnknown() {
	xxx_messageInfo_Transfer.DiscardUnknown(m)
}

var xxx_messageInfo_Transfer proto.InternalMessageInfo

func (m *Transfer) GetType() TransferType {
	if m != nil {
		return m.Type
	}
	return TransferType_unspecified
}

func (m *Transfer) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

func (m *Transfer) GetParticipants() map[string][]byte {
	if m != nil {
		return m.Participants
	}
	return nil
}

//Asset Definitons
type Wallet struct {
	Description          string   `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
	Principal            []byte   `protobuf:"bytes,2,opt,name=principal,proto3" json:"principal,omitempty"`
	Creditor             []byte   `protobuf:"bytes,3,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Initiator            []byte   `protobuf:"bytes,4,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Address              []byte   `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Counterparty         []byte   `protobuf:"bytes,6,opt,name=counterparty,proto3" json:"counterparty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wallet) Reset()         { *m = Wallet{} }
func (m *Wallet) String() string { return proto.CompactTextString(m) }
func (*Wallet) ProtoMessage()    {}
func (*Wallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{3}
}

func (m *Wallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wallet.Unmarshal(m, b)
}
func (m *Wallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wallet.Marshal(b, m, deterministic)
}
func (m *Wallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallet.Merge(m, src)
}
func (m *Wallet) XXX_Size() int {
	return xxx_messageInfo_Wallet.Size(m)
}
func (m *Wallet) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallet.DiscardUnknown(m)
}

var xxx_messageInfo_Wallet proto.InternalMessageInfo

func (m *Wallet) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Wallet) GetPrincipal() []byte {
	if m != nil {
		return m.Principal
	}
	return nil
}

func (m *Wallet) GetCreditor() []byte {
	if m != nil {
		return m.Creditor
	}
	return nil
}

func (m *Wallet) GetInitiator() []byte {
	if m != nil {
		return m.Initiator
	}
	return nil
}

func (m *Wallet) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Wallet) GetCounterparty() []byte {
	if m != nil {
		return m.Counterparty
	}
	return nil
}

type TrusteeGroup struct {
	TrusteeID            [][]byte `protobuf:"bytes,1,rep,name=TrusteeID,proto3" json:"TrusteeID,omitempty"`
	Threshold            int64    `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrusteeGroup) Reset()         { *m = TrusteeGroup{} }
func (m *TrusteeGroup) String() string { return proto.CompactTextString(m) }
func (*TrusteeGroup) ProtoMessage()    {}
func (*TrusteeGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{4}
}

func (m *TrusteeGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrusteeGroup.Unmarshal(m, b)
}
func (m *TrusteeGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrusteeGroup.Marshal(b, m, deterministic)
}
func (m *TrusteeGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrusteeGroup.Merge(m, src)
}
func (m *TrusteeGroup) XXX_Size() int {
	return xxx_messageInfo_TrusteeGroup.Size(m)
}
func (m *TrusteeGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_TrusteeGroup.DiscardUnknown(m)
}

var xxx_messageInfo_TrusteeGroup proto.InternalMessageInfo

func (m *TrusteeGroup) GetTrusteeID() [][]byte {
	if m != nil {
		return m.TrusteeID
	}
	return nil
}

func (m *TrusteeGroup) GetThreshold() int64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

type IDDoc struct {
	AuthenticationReference string   `protobuf:"bytes,1,opt,name=AuthenticationReference,proto3" json:"AuthenticationReference,omitempty"`
	BeneficiaryECPublicKey  []byte   `protobuf:"bytes,2,opt,name=BeneficiaryECPublicKey,proto3" json:"BeneficiaryECPublicKey,omitempty"`
	SikePublicKey           []byte   `protobuf:"bytes,3,opt,name=SikePublicKey,proto3" json:"SikePublicKey,omitempty"`
	BLSPublicKey            []byte   `protobuf:"bytes,4,opt,name=BLSPublicKey,proto3" json:"BLSPublicKey,omitempty"`
	Timestamp               int64    `protobuf:"varint,5,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *IDDoc) Reset()         { *m = IDDoc{} }
func (m *IDDoc) String() string { return proto.CompactTextString(m) }
func (*IDDoc) ProtoMessage()    {}
func (*IDDoc) Descriptor() ([]byte, []int) {
	return fileDescriptor_610ca40ce07a87fe, []int{5}
}

func (m *IDDoc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDDoc.Unmarshal(m, b)
}
func (m *IDDoc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDDoc.Marshal(b, m, deterministic)
}
func (m *IDDoc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDDoc.Merge(m, src)
}
func (m *IDDoc) XXX_Size() int {
	return xxx_messageInfo_IDDoc.Size(m)
}
func (m *IDDoc) XXX_DiscardUnknown() {
	xxx_messageInfo_IDDoc.DiscardUnknown(m)
}

var xxx_messageInfo_IDDoc proto.InternalMessageInfo

func (m *IDDoc) GetAuthenticationReference() string {
	if m != nil {
		return m.AuthenticationReference
	}
	return ""
}

func (m *IDDoc) GetBeneficiaryECPublicKey() []byte {
	if m != nil {
		return m.BeneficiaryECPublicKey
	}
	return nil
}

func (m *IDDoc) GetSikePublicKey() []byte {
	if m != nil {
		return m.SikePublicKey
	}
	return nil
}

func (m *IDDoc) GetBLSPublicKey() []byte {
	if m != nil {
		return m.BLSPublicKey
	}
	return nil
}

func (m *IDDoc) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("protobuffer.AssetType", AssetType_name, AssetType_value)
	proto.RegisterEnum("protobuffer.TransferType", TransferType_name, TransferType_value)
	proto.RegisterType((*Signature)(nil), "protobuffer.Signature")
	proto.RegisterType((*Asset)(nil), "protobuffer.Asset")
	proto.RegisterType((*Transfer)(nil), "protobuffer.Transfer")
	proto.RegisterMapType((map[string][]byte)(nil), "protobuffer.Transfer.ParticipantsEntry")
	proto.RegisterType((*Wallet)(nil), "protobuffer.Wallet")
	proto.RegisterType((*TrusteeGroup)(nil), "protobuffer.TrusteeGroup")
	proto.RegisterType((*IDDoc)(nil), "protobuffer.IDDoc")
}

func init() { proto.RegisterFile("assets.proto", fileDescriptor_610ca40ce07a87fe) }

var fileDescriptor_610ca40ce07a87fe = []byte{
	// 676 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xd1, 0x4e, 0xdb, 0x4a,
	0x10, 0x8d, 0xed, 0x24, 0x90, 0x89, 0x2f, 0x98, 0xbd, 0xf7, 0x52, 0x83, 0xaa, 0x2a, 0x8a, 0x2a,
	0x35, 0x8a, 0x44, 0x2a, 0x51, 0xa9, 0xa2, 0x7d, 0x41, 0xd0, 0xa0, 0x92, 0x52, 0xa9, 0x68, 0x41,
	0xea, 0xf3, 0x62, 0x4f, 0x9a, 0x15, 0x66, 0x6d, 0xed, 0xae, 0xa1, 0xf9, 0xbb, 0x4a, 0xfd, 0x92,
	0x3e, 0xf5, 0x37, 0xaa, 0x5d, 0x3b, 0xd8, 0x2e, 0xf0, 0x64, 0xcf, 0x99, 0x73, 0x66, 0x76, 0xcf,
	0xce, 0x80, 0xcf, 0x94, 0x42, 0xad, 0x26, 0x99, 0x4c, 0x75, 0x4a, 0xfa, 0xf6, 0x73, 0x95, 0xcf,
	0xe7, 0x28, 0x87, 0x37, 0xd0, 0xbb, 0xe0, 0xdf, 0x04, 0xd3, 0xb9, 0x44, 0xf2, 0xbc, 0x16, 0x84,
	0xce, 0xc0, 0x19, 0xf9, 0xb4, 0x96, 0x0d, 0x61, 0xcd, 0x04, 0x28, 0x55, 0xe8, 0x0e, 0xbc, 0x91,
	0x4f, 0x57, 0x21, 0x19, 0x41, 0xe7, 0xc8, 0x74, 0x08, 0xbd, 0x81, 0x33, 0xea, 0xef, 0x93, 0x49,
	0xad, 0xc3, 0xc4, 0x66, 0x68, 0x41, 0x18, 0xfe, 0x74, 0x4b, 0x2a, 0x19, 0x43, 0xfb, 0x72, 0x99,
	0x15, 0x6d, 0x36, 0xf6, 0xb7, 0x1f, 0x4a, 0x4c, 0x96, 0x5a, 0x0e, 0xd9, 0x00, 0x77, 0x36, 0x0d,
	0x5d, 0x7b, 0x20, 0x77, 0x36, 0x25, 0xff, 0x41, 0xe7, 0xcb, 0x9d, 0x40, 0x69, 0xfb, 0xf9, 0xb4,
	0x08, 0xc8, 0x1e, 0x74, 0xbf, 0xb2, 0x24, 0x41, 0x1d, 0xb6, 0xed, 0x31, 0xfe, 0x6d, 0xd4, 0x2c,
	0x52, 0xa7, 0x2d, 0x5a, 0x92, 0xc8, 0x21, 0xf8, 0x97, 0x32, 0x57, 0x1a, 0xf1, 0xa3, 0x4c, 0xf3,
	0x2c, 0xec, 0x58, 0xd1, 0x4e, 0x43, 0x54, 0x27, 0x9c, 0xb6, 0x68, 0x43, 0x40, 0xc6, 0xd0, 0x99,
	0xc5, 0x71, 0x1a, 0x85, 0xdd, 0x47, 0x6e, 0x3d, 0x9b, 0x4e, 0xd3, 0xe8, 0xb4, 0x45, 0x0b, 0x0a,
	0x79, 0x67, 0x9a, 0x31, 0xa1, 0xe6, 0x28, 0x13, 0xae, 0x74, 0xb8, 0x36, 0xf0, 0x46, 0xfd, 0xfd,
	0xff, 0xff, 0x6a, 0x56, 0x10, 0x68, 0x83, 0x7a, 0xbc, 0x05, 0x9b, 0xd6, 0x8f, 0x29, 0xce, 0xb9,
	0xe0, 0x9a, 0xa7, 0x62, 0xf8, 0xdb, 0x81, 0xf5, 0x15, 0x87, 0xec, 0x35, 0x8c, 0xdc, 0x79, 0xb4,
	0x64, 0xcd, 0xcb, 0x17, 0x00, 0x27, 0xdf, 0x33, 0x89, 0x4a, 0xf1, 0x54, 0x58, 0x4f, 0x7b, 0xb4,
	0x86, 0x90, 0x33, 0xf0, 0xcf, 0x99, 0xd4, 0x3c, 0xe2, 0x19, 0x13, 0x5a, 0x85, 0x9e, 0x3d, 0xe9,
	0xab, 0x47, 0xcb, 0x4e, 0xea, 0xcc, 0x13, 0xa1, 0xe5, 0x92, 0x36, 0xc4, 0xbb, 0x87, 0xb0, 0xf5,
	0x80, 0x42, 0x02, 0xf0, 0xae, 0x71, 0x69, 0xcf, 0xdb, 0xa3, 0xe6, 0xd7, 0xbc, 0xe7, 0x2d, 0x4b,
	0x72, 0x2c, 0x9f, 0xb8, 0x08, 0xde, 0xbb, 0x07, 0xce, 0xf0, 0x87, 0xb3, 0x7a, 0x54, 0x32, 0x80,
	0xfe, 0x14, 0x55, 0x24, 0x79, 0x66, 0x3c, 0x28, 0xe5, 0x75, 0xc8, 0x8c, 0x6f, 0x26, 0xb9, 0x30,
	0xcd, 0x92, 0xb2, 0x54, 0x05, 0x90, 0x5d, 0x58, 0x8f, 0x24, 0xc6, 0x5c, 0xa7, 0xab, 0xb9, 0xb9,
	0x8f, 0x8d, 0xd2, 0x7a, 0xcb, 0x4c, 0xb2, 0x5d, 0x28, 0xef, 0x01, 0x33, 0xf8, 0x2c, 0x8e, 0x8d,
	0x41, 0x76, 0x48, 0x7c, 0xba, 0x0a, 0xc9, 0x10, 0xfc, 0x28, 0xcd, 0x85, 0x46, 0x99, 0x31, 0xa9,
	0x97, 0x76, 0x12, 0x7c, 0xda, 0xc0, 0x86, 0x9f, 0x9a, 0x73, 0x66, 0x7a, 0x95, 0xf1, 0x6c, 0x1a,
	0x3a, 0x76, 0x91, 0x2a, 0xc0, 0x64, 0xf5, 0x42, 0xa2, 0x5a, 0xa4, 0x49, 0x6c, 0xef, 0xe0, 0xd1,
	0x0a, 0x18, 0xfe, 0x72, 0xa0, 0x63, 0x27, 0x8b, 0x1c, 0xc0, 0xb3, 0xa3, 0x5c, 0x2f, 0x50, 0x68,
	0x1e, 0x31, 0x73, 0x7b, 0x8a, 0x73, 0x94, 0x28, 0x22, 0x2c, 0x9d, 0x79, 0x2a, 0x4d, 0xde, 0xc2,
	0xf6, 0x31, 0x0a, 0x9c, 0xf3, 0x88, 0x33, 0xb9, 0x3c, 0xf9, 0x70, 0x9e, 0x5f, 0x25, 0x3c, 0x3a,
	0xc3, 0x65, 0x69, 0xd9, 0x13, 0x59, 0xf2, 0x12, 0xfe, 0xb9, 0xe0, 0xd7, 0x58, 0xd1, 0x0b, 0x13,
	0x9b, 0xa0, 0x71, 0xe4, 0xf8, 0xf3, 0x45, 0x45, 0x2a, 0xcc, 0x6c, 0x60, 0xd6, 0x01, 0x7e, 0x83,
	0x4a, 0xb3, 0x9b, 0x62, 0xed, 0x3c, 0x5a, 0x01, 0xe3, 0xd7, 0xd0, 0xbb, 0xdf, 0x7f, 0x02, 0xd0,
	0xbd, 0xb3, 0xcf, 0x1f, 0xb4, 0x48, 0x1f, 0xd6, 0x74, 0xe1, 0x53, 0xe0, 0x90, 0x1e, 0x74, 0xb8,
	0xd9, 0xac, 0xc0, 0x1d, 0xdf, 0x56, 0xbb, 0x65, 0x35, 0x9b, 0xd0, 0xcf, 0x85, 0xca, 0x30, 0xe2,
	0x73, 0x8e, 0x71, 0xd0, 0x22, 0x1b, 0x00, 0x0a, 0xb5, 0x4e, 0xf0, 0x3c, 0x57, 0x8b, 0xc0, 0xa9,
	0xc7, 0x49, 0x12, 0xb8, 0x24, 0x00, 0x5f, 0x97, 0x05, 0x2c, 0xc3, 0x33, 0x25, 0x0c, 0x62, 0x81,
	0x24, 0x09, 0xda, 0x64, 0x1d, 0xda, 0xea, 0x8e, 0x65, 0x41, 0xc7, 0xfc, 0x25, 0x29, 0x8b, 0x83,
	0xee, 0x55, 0xd7, 0xae, 0xc4, 0x9b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xa9, 0xf9, 0x3a,
	0x5e, 0x05, 0x00, 0x00,
}
